var COEF_SINAPSIS_ENTRENAMIENTO =  0;
var COEF_SINAPSIS_UMBRAL_PESO =  0.2;
var COEF_NEURONA_UMBRAL_ACTIVACION =  0;
var PESO_DENDRITA_CERCANA =  0.384;
var PESO_DENDRITA_INHIBIDORA =  -0.275;
var PESO_DENDRITA_ENTRADA =  1;
